### ISSUE TITLE
Why does fluminurs.exe force close after I managed to enter my username and password??

### ISSUE THREAD

**Issue by cupcakeslove128** [indocomsoft/fluminurs#405]
I wasn't able to use it to download anything as it just said Hi, xxxxxxxx (my name) ! and the .exe closes ??

**Comment by cupcakeslove128** [comment]
@indocomsoft

**Comment by indocomsoft** [comment]
To find out about the options, run `fluminurs.exe --help`. It's pretty similar to other CLI tools out there!


Footnote:
This pattern of accepting flag `--help` is common in Unix tools.

For Windows/DOS, the convention is to use `/help`.

This *might* work with fluminurs, but I'm not sure because I use a library to parse the flags

**Comment by indocomsoft** [comment]
Note:

If you're double clicking the app, that wouldn't work since this app is not a graphical app. It's meant to be run from command line, so either run it from the command prompt, or powershell
