### ISSUE TITLE
Can fluminurs download Webcasts and Multimedia?

### ISSUE THREAD

**Issue by cupcakeslove128** [indocomsoft/fluminurs#408]
I have tried following the answers given by you, @indocomsoft and so far downloaded only files but not Webcasts and Multimedia. I know that Fluimus_CLI can download webcasts and multimedia but can Fluminurs download those too?

**Comment by cupcakeslove128** [comment]
@indocomsoft

**Comment by indocomsoft** [comment]
Hi there, if it's not listed in the `--help` usage page, then that feature is most likely not implemented.

There is an issue covering this issue actually: https://github.com/indocomsoft/fluminurs/issues/60

Feel free to contribute and submit a PR to implement this functionality. All the recent new features in fluminurs have been done by contributors, for example https://github.com/indocomsoft/fluminurs/pull/89.

While fluminus and fluminurs had common origin (I started implementing the Elixir version, then ported it to Rust), at this point in time, they have diverged significantly, with different feature sets that intersect each other instead of one being the proper subset of the other.

I hack mostly on `fluminus` (the Elixir version) because that's the one I actively use. I started this project mostly to learn Rust. My extent of involvement with this project right now is just keeping the dependencies up-to-date, as well as reviewing and merging PR's from contributors. At the moment, I don't have any plan to port the features in fluminus to fluminurs, but people are welcome to contribute and make it happen!
